kind: Service
apiVersion: v1
metadata:
  labels:
    app: scrum-master-jr
  name: scrum-master-jr
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: scrum-master-jr
