name: Generate End of Sprint Report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v4
        with:
          python-version: 3.9.15
      - env:
            CURRENT_SPRINT: ${{ vars.CURRENT_SPRINT }}
            JIRA_HOST: ${{ vars.JIRA_HOST }}
            JIRA_USER: ${{ secrets.JIRA_USER }}
            JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
            TEMPLATE_PAGE_ID: ${{ vars.TEMPLATE_PAGE_ID }}
            PARENT_PAGE_ID: ${{ vars.PARENT_PAGE_ID }}
        id: script
        run: |
          echo "POTENTIAL_URL=$( pipenv run python ./generate_eos_report_page.py | tail -n 1 )" >> $GITHUB_ENV
          echo $GITHUB_ENV
      - name: Get Page URL
        uses: kaisugi/action-regex-match@v1.0.0
        id: page-url
        with:
          text: ${{ env.POTENTIAL_URL }}
          regex: 'https://.*$'
          flags: "i"
      - name: Slack (Success) Notification
        if: startsWith(steps.page-url.outputs.group1, 'https')
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.TEAM_LEADS_SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "The latest End of Sprint Report is available <${{ steps.page-url.outputs.group1 }}|here> but is still pending metrics"
                  }
                }
              ]
            }
