name: Generate End of Sprint Report

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v4
        with:
          python-version: 3.9.15
      - env:
            CURRENT_SPRINT: ${{ vars.CURRENT_SPRINT }}
            JIRA_HOST: ${{ secrets.JIRA_HOST }}
            JIRA_USER: ${{ secrets.JIRA_USER }}
            JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
            TEMPLATE_PAGE_ID: ${{ secrets.TEMPLATE_PAGE_ID }}
            PARENT_PAGE_ID: ${{ secrets.PARENT_PAGE_ID }}
        run: |
          echo "Current Sprint = $CURRENT_SPRINT"
          echo "PATH = $PATH"
          ls -la
          pipenv run python ./generate_eos_report_page.py
