name: Refactor Comment Reminder

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  pr_commented:
    name: PR comment
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'refactor')
    runs-on: ubuntu-latest
    steps:
       - name: Create or update a comment
         uses: taoliujun/action-unique-comment@v1
         with:
            uniqueIdentifier: 'refactor reminder'
            body: Hey there! Noticed a mention of "refactor" in this PR. Just a quick reminder |
                  Before diving into any large or unplanned refactoring, please check in with the team first. It is important that we collectively decide whether to
                    ✅ Accept the increased scope now, or
                    ⏳ Defer the refactor to a later time.
                  This helps us stay aligned and keep our priorities clear. Thanks for keeping the team in the loop!