name: Run End of Sprint Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * 4"
  
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v4
        with:
          python-version: 3.9.15
      - id: update_eos_page
        env:
            JIRA_HOST: ${{ vars.JIRA_HOST }}
            JIRA_USER: ${{ secrets.JIRA_USER }}
            JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
            PARENT_PAGE_ID: ${{ vars.PARENT_PAGE_ID }}
        run: |
          pipenv run python ./run_end_of_sprint_metrics.py 2>&1 | tee ./eos_logs.txt
          echo "POTENTIAL_URL=$( tail -n 1 eos_logs.txt )" >> $GITHUB_ENV
      - name: Get Page URL
        uses: kaisugi/action-regex-match@v1.0.0
        id: page-url
        with:
          text: ${{ env.POTENTIAL_URL }}
          regex: 'https:\/\/[\w\.\/\+~]*Sprint\+(\d+)\+Report.*$'
          flags: "i"
      - id: all_data_script
        env:
            JIRA_HOST: ${{ vars.JIRA_HOST }}
            JIRA_USER: ${{ secrets.JIRA_USER }}
            JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
            PARENT_PAGE_ID: ${{ vars.PARENT_PAGE_ID }}
            SPRINT_NUMBER: ${{ steps.page-url.outputs.group1 }}
        run: |
          SPRINT_NUMBER=$(printf %02d $SPRINT_NUMBER)
          echo $SPRINT_NUMBER
          pipenv run python ./all_data.py "$(date +'%y').$SPRINT_NUMBER" 2>&1 | tee ./all_data_logs.txt
      - name: Read package.json
        if: startsWith(steps.page-url.outputs.match, 'https')
        id: file
        uses: juliangruber/read-file-action@v1
        with:
          path: ./all_sprint_data.txt
      - name: Prep Metrics Blob
        id: metrics
        uses: ashley-taylor/regex-property-action@v1.3
        with:
          value: ${{ steps.file.outputs.content }}
          regex: '\s*\n\s*'
          replacement: '\n'
      - name: Report Metrics Results
        if: startsWith(steps.page-url.outputs.match, 'https')
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SCRUM_PRIVATE_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Here are the latest Sprint Metrics! \n```${{ steps.metrics.outputs.value }}```"
                  }
                }
              ]
            }
      - name: Notify Leads
        if: startsWith(steps.page-url.outputs.match, 'https')
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.TEAM_LEADS_SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Metrics have been posted in the <${{ steps.page-url.outputs.match }}|End of Sprint Report>"
                  }
                }
              ]
            }
        
