name: Test Workflow 

on:
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Test Step 1
        run: |
          echo "Current Sprint = ${{ vars.CURRENT_SPRINT }}"
